org: nam268ek
app: demo-app-theme-api
service: demo-app-theme-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    environment:
      DB_URL: ${env:DB_URL}
      SECRET_KEY: ${env:SECRET_KEY}
      CLOUD_NAME: ${env:CLOUD_NAME}
      API_KEY: ${env:API_SECRET}
      API_SECRET: ${env:API_SECRET}
      TOKEN_EXPIRE: ${env:TOKEN_EXPIRE}
      REFRESH_TOKEN_EXPIRE: ${env:REFRESH_TOKEN_EXPIRE}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
